[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_i = 1

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo      = 'thinca/vim-prettyprint'
on_cmd    = ['PP', 'PrettyPrint']


[[plugins]]
repo = 'kovisoft/slimv'
on_ft = ['lisp', 'clojure', 'scheme']
hook_source = '''
let g:slimv_swank_cmd = '!osascript -e "tell application \"Terminal\" to do script \"sbcl --load ~//.cache/dein/repos/github.com/kovisoft/slimv/slime/start-swank.lisp\""'
let g:slimv_repl_split = 4
'''

[[plugins]]
repo  = 'Quramy/tsuquyomi'
on_ft = ['typescript']

[[plugins]]
repo  = 'jiangmiao/simple-javascript-indenter'
on_ft = ['javascript', 'html']

[[plugins]]
repo  = 'jelera/vim-javascript-syntax'
on_ft = ['javascript', 'html']

[[plugins]]
repo  = 'kana/vim-filetype-haskell'
on_ft = ['haskell']

[[plugins]]
repo  = 'ujihisa/neco-ghc'
on_ft = ['haskell']

[[plugins]]
repo  = 'derekwyatt/vim-scala'
on_ft = ['scala']

